import Head from 'next/head'

import HeaderCompany from '@/components/HeaderCompany'

import * as S from "./styles"
import { Carousel } from '@/components/Carousel'
import Card from '@/components/Card'
import Button from '@/components/ButtonLink'
import { Eye } from '@/components/images/icons/vectors'
import Paragraph from '@/components/Paragraph'
import TitleH2 from '@/components/TitleH2'

const Company = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Section1Wrapper>
        <S.Content>
          <HeaderCompany />

          <S.Snippet>
            <TitleH2>
              Sobre a experiência
            </TitleH2>
            <Paragraph>
              Lorem linguiça é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica,
            </Paragraph>
          </S.Snippet>

          <S.CarouselArea>
            <TitleH2>
              Projetos
            </TitleH2>
            <Carousel>
              <Card
                title="IP Sync Cloudflare"
                description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
                background="/images/ip_sync_cloudflare.png"
                buttons={<>
                  <Button text='Vizualizar' icon={<Eye size='20' />} href="/project"/>
                </>}
              />
              <Card
                title="IP Sync Cloudflare"
                description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
                background="/images/ip_sync_cloudflare.png"
                buttons={<>
                  <Button text='Vizualizar' icon={<Eye size='20' />} href="/project"/>
                </>}
              />
              <Card
                title="IP Sync Cloudflare"
                description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
                background="/images/ip_sync_cloudflare.png"
                buttons={<>
                  <Button text='Vizualizar' icon={<Eye size='20' />} href="/project"/>
                </>}
              />
              <Card
                title="IP Sync Cloudflare"
                description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
                background="/images/ip_sync_cloudflare.png"
                buttons={<>
                  <Button text='Vizualizar' icon={<Eye size='20' />} href="/project"/>
                </>}
              />
              <Card
                title="IP Sync Cloudflare"
                description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
                background="/images/ip_sync_cloudflare.png"
                buttons={<>
                  <Button text='Vizualizar' icon={<Eye size='20' />} href="/project"/>
                </>}
              />
            </Carousel>
          </S.CarouselArea>
        </S.Content>
      </S.Section1Wrapper>
    </>
  )
}

export default Company;
