import Head from 'next/head'

import HeaderCompany from '@/components/HeaderCompany'

import * as S from "./styles"

const Company = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Section1Wrapper>
        <S.Content>
          <HeaderCompany />
        </S.Content>
      </S.Section1Wrapper>
    </>
  )
}

export default Company;
