export { default as Linkedin } from "./linkedin"
export { default as Discord } from "./discord"
export { default as Email } from "./email"
export { default as Eye } from "./eye"
export { default as ArrowLeft } from "./arrow-left"
export { default as ArrowRight } from "./arrow-right"
export { default as Github } from "./github"
