import Button from '@/components/Button';
import Card from '@/components/Card';
import { Carousel } from '@/components/Carousel';
import { Eye } from '@/components/images/icons/vectors';
import Section1 from '@/components/Section1';
import Section2 from '@/components/Section2';
import Head from 'next/head'
import { useRouter } from 'next/router';
import { useEffect } from 'react';

import * as S from "./styles";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    let timerID: number = 0;
    const options: IntersectionObserverInit = {
      root: document.querySelector("main"), rootMargin: "40px", threshold: 1
    };

    const observer = new IntersectionObserver(elements => {
      const [element] = elements;
      clearTimeout(timerID);

      timerID = setTimeout(() => {
        if (element.isIntersecting)
          router.replace(`/#${element.target.id}`, undefined, { shallow: true })
      }, 3500) as unknown as number;
    }, options);

    Array.from(document.querySelectorAll("main > section")).forEach((element) => {
      observer.observe(element);
    })

    return () => {
      observer.disconnect()
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Section id="who-am-I">
        <Section1 />
      </S.Section>
      <S.Section id="skills">
        <Section2 />
      </S.Section>
      <S.Section id="portfolio">
        <Carousel>
          <Card
            title="IP Sync Cloudflare"
            description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
            background="/images/ip_sync_cloudflare.png"
            buttons={[
              <Button text='Vizualizar' icon={<Eye size='20' />} />,
              <Button text='Vizualizar' icon={<Eye size='20' />} />
            ]}
            profilePicture={<Eye size='29' color='white' />}
          />
          <Card
            title="IP Sync Cloudflare"
            description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
            background="/images/ip_sync_cloudflare.png"
            buttons={[
              <Button text='Vizualizar' icon={<Eye size='20' />} />,
              <Button text='Vizualizar' icon={<Eye size='20' />} />
            ]}
            profilePicture={<Eye size='29' color='white' />}
          />
          <Card
            title="IP Sync Cloudflare"
            description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
            background="/images/ip_sync_cloudflare.png"
            buttons={[
              <Button text='Vizualizar' icon={<Eye size='20' />} />,
              <Button text='Vizualizar' icon={<Eye size='20' />} />
            ]}
            profilePicture={<Eye size='29' color='white' />}
          />
          <Card
            title="IP Sync Cloudflare"
            description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
            background="/images/ip_sync_cloudflare.png"
            buttons={[
              <Button text='Vizualizar' icon={<Eye size='20' />} />,
              <Button text='Vizualizar' icon={<Eye size='20' />} />
            ]}
            profilePicture={<Eye size='29' color='white' />}
          />
          <Card
            title="IP Sync Cloudflare"
            description="Scheduler para realizar a sincronização periódica de endereços IPs de servidores sem endereçamento estático na Cloudflare"
            background="/images/ip_sync_cloudflare.png"
            buttons={[
              <Button text='Vizualizar' icon={<Eye size='20' />} />,
              <Button text='Vizualizar' icon={<Eye size='20' />} />
            ]}
            profilePicture={<Eye size='29' color='white' />}
          />
        </Carousel>

      </S.Section>
    </>
  )
}
