import Section1 from '@/components/Section1';
import Section2 from '@/components/Section2';
import Section3 from '@/components/Section3';
import Head from 'next/head'
import { useRouter } from 'next/router';
import { useEffect } from 'react';

import * as S from "./styles";

export default function Home() {
  const router = useRouter();

  useEffect(() => {

  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Section id="who-am-I">
        <Section1 />
      </S.Section>
      <S.Section id="skills">
        <Section2 />
      </S.Section>
      <S.Section id="portfolio">
        <Section3 />
      </S.Section>
    </>
  )
}
