import Head from 'next/head'

import * as S from "./styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Section id="who-am-I" $bgColor='red'></S.Section>
      <S.Section id="skills" $bgColor='green'></S.Section>
      <S.Section id="portfolio" $bgColor='blue'></S.Section>
    </>
  )
}
